### ISSUE TITLE
Plugin crash when deleting folder

### ISSUE THREAD

**Issue by JayNewstrom** [JayNewstrom/json#34]
Relevant part of the stacktrace: 
```
Caused by: java.lang.IndexOutOfBoundsException: Index: 8, Size: 8
        at com.jaynewstrom.json.compiler.FileKt.relativePath(File.kt:6)
        at com.jaynewstrom.json.gradle.JsonTask.relativePackage(JsonTask.kt:76)
        at com.jaynewstrom.json.gradle.JsonTask.access$relativePackage(JsonTask.kt:22)
        at com.jaynewstrom.json.gradle.JsonTask$execute$3.execute(JsonTask.kt:62)
        at com.jaynewstrom.json.gradle.JsonTask$execute$3.execute(JsonTask.kt:22)
        at org.gradle.api.internal.changedetection.changes.ChangesOnlyIncrementalTaskInputs.doRemoved(ChangesOnlyIncrementalTaskInputs.java:54)
        at org.gradle.api.internal.changedetection.changes.StatefulIncrementalTaskInputs.removed(StatefulIncrementalTaskInputs.java:52)
        at org.gradle.api.internal.changedetection.changes.ChangesOnlyIncrementalTaskInputs.removed(ChangesOnlyIncrementalTaskInputs.java:27)
        at com.jaynewstrom.json.gradle.JsonTask.execute(JsonTask.kt:61)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:168)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:303)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:295)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:177)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 98 more

```

This happens when there is no json folder, but the plugin is applied.

**Comment by JayNewstrom** [comment]
This no longer happens.
